#! /bin/sh

if [ -z "$1" ] || [ "$1" = "-h" ]; then
    echo "collate –– wrapper for imagemagick 'convert',"
    echo "           combines multiple images/pdfs to one pdf."
    echo "usage: collate <images/documents> <optional output pdf>"
    echo ""
    echo "examples:"
    echo "- collate single image to pdf (image to pdf conversion):"
    echo "  collate my-image.png my-image.pdf"
    echo "- collate multiple images to one pdf (use quote):"
    echo "  collate '*.png' output.pdf"
    exit
fi

output=$2
if [ -z "$output" ]; then
    output="collated.pdf"
fi

# verify dependencies
hash convert 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS convert"; }
if [ ! -z "$MISSING_DEPS" ]; then
    echo "whoops! missing dependencies:"
    echo $MISSING_DEPS
    exit
fi

convert "$1" $output
echo "collate command finished. output: $output"
