#!/bin/sh

if [ "$1" = "-h" ]; then
    echo "cra is alias to 'create-react-app' command."
    echo "to install the command, run:"
    echo "npm install -g create-react-app"
    exit
fi

create-react-app $@