#!/usr/bin/env sh

# usage:
# 1. adjust permission: `chmod +x diffy` 
# 2. copy or link this file to your path (ie. `ln -s diffy /usr/local/bin`)
# 3. run diffy to upload your `git diff` to diffy

if git rev-parse --git-dir > /dev/null 2>&1; then
  DIFF_FILE=/tmp/to_diffy.diff
  DIFF_COMMAND="git diff"
  if [ -z "$1" ]
    then
    	`$DIFF_COMMAND > $DIFF_FILE`
  else
  	DIFF_COMMAND=$@
    	`$DIFF_COMMAND > $DIFF_FILE`
  fi

  echo "uploading output of '$DIFF_COMMAND' to diffy.org.."

  # sample response:
  # Found. Redirecting to /diff/4hrag1lvv7lgyt81v6t0fqolxr
  diffy_response=`curl -s -F diffFile=@$DIFF_FILE https://diffy.org/new`

  replacer=diffy.org/diff
  echo "${diffy_response/\/diff/$replacer}"
else
  echo "diffy error: this directory is not a git repo"
fi
