#!/bin/sh

# make symlink of current directory in $GOPATH/src
# e.g. create `$GOPATH/src/github.com/my-package`:
# `cd ~/path-to/my-package && golink github.com/wzulfikar`
if [ -z "$1" ] || [ "$1" = "-h" ];then
    echo "golink creates symlink of current directory to gopath."
    echo "usage: golink <gopath directory>"
    echo "example: golink github.com/my-package"
    exit 0
fi

workdir="$(pwd)"
gopath_link="$GOPATH/src/$1"
symlink="$gopath_link/$(basename $workdir)"

# create golink registry if not exists
golink_file="$GOPATH/.golink"
[ ! -f "$golink_file" ] && touch "$golink_file"

# handle `golink where` command
if [ "$1" = "where" ]; then
    symlink="$(cat "$golink_file" | grep -E "^$workdir:" | sed "s#$workdir:##")"
    if [ -z "$symlink" ]; then
        echo "no golink available for current directory."
        exit 1
    fi
    echo $symlink
    exit 0
fi

# abort symlink creation if symlink already exists
if [ -d "$symlink" ]; then
    echo "symlink already exist:"
    ls -la "$symlink"
    exit 1
fi

# create symlink
ln -s "$workdir" "$gopath_link"

# add symlink to registry
echo "$workdir:$symlink" >> "$golink_file"

echo "symlink created: $symlink"
