#!/bin/sh

# usage: photon -u http://example.com -l 2 -t 10 --wayback

# try to use default path
if [ -z "$PYTHON_PHOTON_PATH" ]; then
    # reflect the executable to get dir in attempt
    # to reach default qotd word list –– assuming the
    # qotd executable is cloned from github directly
    PYTHON_PHOTON_PATH=/photon/photon.py
fi

# fail if path doesn't exist
if [ ! -e "$PYTHON_PHOTON_PATH" ]; then
    echo "PYTHON_PHOTON_PATH is not set. Tried to use default"
    echo "photon dir at $PYTHON_PHOTON_PATH but it doesn't exist."
    echo ""
    echo "To continue, download or clone photon from"
    echo "https://github.com/s0md3v/Photon and use its path"
    echo "as the value of your PYTHON_PHOTON_PATH env var."
    exit
fi

python3 $PYTHON_PHOTON_PATH $@
