#!/usr/bin/env sh

# usage:
# 1. adjust file permission (if you have not): `chmod +x qotd`
# 2. copy or link this file to your path (ie. `ln -s $(pwd)/qotd /usr/local/bin`)
# 3. run qotd

if [ -z "$1" ]; then
	# replace this path to your own
	d=~/code/github/lab/bash/qotd-words.txt

	rand=$[($RANDOM % `wc -l $d|sed "s/[^0-9]//g"`)+1]

	# `printf` ansi escape code for green
	# so the qotd will be printed in green color.
	# for other escape code, see https://en.wikipedia.org/wiki/ANSI_escape_code
	printf '\033[0;32m'
	sed $rand"q;d" $d
	printf '\033[0;0m' # no color
else
	echo "qotd - display quote of the day"
  	echo "usage: qotd"
fi
