#!/bin/sh

hash awk 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS awk"; }
hash curl 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS curl"; }
if [ ! -z "$MISSING_DEPS" ]; then
	echo "[ERROR] missing dependencies:"
	echo $MISSING_DEPS
	exit
fi

timestamp=$(date +"%Y-%m-%dT%H:%M:%S%z")

if [ -z "$API_KEY" ]; then
	echo '{"timestamp":"'$timestamp'","error":"API_KEY must be vultr api key or path to api key file."}'
	exit 1
fi

# get api key from file if API_KEY is file
if [ -f "$API_KEY" ]; then
	if [ ! -r "$API_KEY" ]; then
		echo '{"timestamp":"'$timestamp'","error":"api key file ('$API_KEY') is not readable."}'
		exit 1
	fi
	API_KEY=$(cat $API_KEY)
fi

# send curl with timeout
timeout_seconds=15
json=$(curl --max-time $timeout_seconds -Ssq -H API-Key:$API_KEY https://api.vultr.com/v1/account/info)

curl_exit_code=$?
if [ "$curl_exit_code" != "0" ]; then
	if [ "$curl_exit_code" = "28" ]; then
		echo '{"timestamp":"'$timestamp'","error":"curl timeout after '$timeout_seconds' seconds."}'
	else
		echo '{"timestamp":"'$timestamp'","error":"curl error '$curl_exit_code'"}'
	fi
	exit 1
fi

if [ -z "$(echo $json | awk '/"balance":.+/')" ]; then
	echo '{"timestamp":"'$timestamp'","error":"'$json'"}'
	exit 1
fi

echo $json | awk '{
	# append "timestamp" field to vultr json response
	sub("balance", "timestamp\":\"'$timestamp'\",\"balance");
	print $0;
}'
