#!/usr/bin/env sh

# eg. `watch-sh '*.php' 'say ha'`

if [ -z $1 ]; then
    echo "watchpy2 –– watch directory and run python3 on change"
    echo "usage: watchpy2 <file to run> <pattern to watch - optional>"
    echo ""
    echo "examples:"
    echo "  watchpy2 main.py"
    echo "  watchpy2 main.py ."
    echo "  watchpy2 main.py src/mymodule"
    echo ""
    echo "dependencies:"
    echo "  entr - run tests whenever files change (https://github.com/clibs/entr)"
    exit
fi

if [ ! -f "$1" ]; then
    echo "[ERROR] $1 is not a file"
    exit
fi

WATCH_DIR=$2
if [ -z "$WATCH_DIR" ] || [ "$WATCH_DIR" == "." ]; then
    WATCH_DIR=.
    FILES="find ."
elif [ -f "$WATCH_DIR" ]; then
    FILES="find $WATCH_DIR"
else
    FILES="find . -name $WATCH_DIR"
fi

if [ $($FILES | wc -l) -eq 0 ]; then
    echo "[ERROR] cannot find any file from '$WATCH_DIR'"
    exit
fi

NC='\033[0;0m' # no color
GREEN='\033[0;32m'

FILENAME=$1

MSG='\n→ Watching python (using entr)..$NC'
BIN="python2"
COMMAND="clear && echo '${GREEN}Output of ‘$@’:$NC' && $BIN $@"

eval "$FILES | entr sh -c \"$COMMAND; printf '$MSG';\""
