#!/usr/bin/env sh

# usage:
# 1. adjust file permission (if you have not): `chmod +x diffy`
# 2. copy or link this file to your path (ie. `ln -s $(pwd)/watchgo /usr/local/bin`)
# 3. run watchgo <file>

if [ -z "$1" ]; then
    echo "watchgo –– watch directory and run 'go run <file>' on change"
    echo "usage: watchgo  <file to run> <pattern to watch - optional>"
    echo ""
    echo "examples:"
    echo "  watchgo main.go"
    echo "  watchgo main.go src/mymodule.go"
    echo ""
    echo "dependencies:"
    echo "  entr - run tests whenever files change (https://github.com/clibs/entr)"
    exit
fi

if [ ! -f "$1" ]; then
    echo "[ERROR] $1 is not a file"
    exit
fi

WATCH_DIR=$2
if [ -z "$WATCH_DIR" ] || [ "$WATCH_DIR" == "." ]; then
    WATCH_DIR=.
    FILES="find ."
elif [ -f "$WATCH_DIR" ]; then
    FILES="find $WATCH_DIR"
else
    FILES="find . -name $WATCH_DIR"
fi

NC='\033[0;0m' # no color
GREEN='\033[0;32m'

MSG='\n→ Watching go (using entr)..$NC'
BANNER='${GREEN}Output of \"$*\":$NC'

COMMAND="clear && echo '$BANNER' && go run $1"
eval "$FILES | entr sh -c \"$COMMAND; printf '$MSG';\""
